name: inset_shell
description: "Feature packed minimalist bar and widgets for linux made with flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  wayland_layer_shell: ^1.0.1
  flutter_inner_shadow: ^0.0.1
  desktop_multi_window: ^0.2.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  inner_shadow_container: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true